import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Card
 * Id: ff98500d-a517-4c46-822c-1cedeeb41cf0
 * Codename: choice_option
 */
export type Card = IContentItem<{
  /**
   * Description (text)
   * Required: true
   * Id: cde986a9-6f6a-41e3-b847-0e6a669aa162
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * Image (asset)
   * Required: false
   * Id: 43685bfd-b08e-4287-a4df-2e99fe605270
   * Codename: image
   */
  image: Elements.AssetsElement;
}>;
