import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HabitList } from './habit_list';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Habit
 * Id: 3ca60cfe-e622-4e5f-a0d6-24f86634da4f
 * Codename: habit
 */
export type Habit = IContentItem<{
  /**
   * Description (text)
   * Required: false
   * Id: d3a7b871-929f-4e36-ad8e-22e19d6df100
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * habit list items (modular_content)
   * Required: false
   * Id: e5b5ede8-89c2-47f2-b9f2-c50d73e26f46
   * Codename: habit_list_items
   */
  habit_list_items: Elements.LinkedItemsElement<HabitList>;

  /**
   * Headline (text)
   * Required: false
   * Id: eeda7f2d-6816-4b38-85b2-af6ed60749c6
   * Codename: headline
   */
  headline: Elements.TextElement;

  /**
   * showcase Image (asset)
   * Required: true
   * Id: 00505385-d696-47ce-bab5-f4738439fea1
   * Codename: showcase_image
   */
  showcase_image: Elements.AssetsElement;
}>;
