import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Button } from '../content-type-snippets/button';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Introduction Section
 * Id: 71eecbdd-8624-421a-8235-cf8cfd4f7b8e
 * Codename: hero_introduction
 */
export type IntroductionSection = IContentItem<{
  /**
   * description (text)
   * Required: false
   * Id: c9895f3b-2191-473b-a329-9563320e802e
   * Codename: description
   */
  description: Elements.TextElement;

  /**
   * hero image or logo (asset)
   * Required: false
   * Id: b8776382-d0a9-42c9-bca3-eefbb9cd3e0b
   * Codename: hero_image
   */
  heroImage: Elements.AssetsElement;

  /**
   * Tagline (text)
   * Required: true
   * Id: e244b4e7-cfad-4cf7-a2a6-2453a674ceb9
   * Codename: tagline
   */
  tagline: Elements.TextElement;
}> &
  Button;
