/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Asset
 * Id: 34854ee5-b569-465e-a1c8-c3b0b2591a15
 * Codename: asset_
 */
export type Asset = 'food' | 'home' | 'recycle_repurpose_reuse' | 'save_energy';
