/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Sustainability Categories
 * Id: 8b9ee8d1-29b3-40b0-b649-e729b22246f7
 * Codename: sustainability_categories
 */
export type SustainabilityCategories =
  | 'food_'
  | 'generic_habits'
  | 'recycle'
  | 'repurpose'
  | 'reuse'
  | 'save_energy'
  | 'save_water';
