import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Button
 * Id: 7d93139f-749c-4e42-baa7-c87df6f36c1f
 * Codename: button
 */
export type Button = IContentItem<{
  /**
   * Button Text (text)
   * Required: false
   * Id: 41b61d48-dc48-4f06-a6e9-f2903ff2f482
   * Codename: button__button_text
   */
  button__button_text: Elements.TextElement;

  /**
   * Button URL (text)
   * Required: false
   * Id: f8783aa9-4ae2-40b7-a783-8de6b1a12311
   * Codename: button__button_url
   */
  button__button_url: Elements.TextElement;
}>;
