/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const assetFolders = {
  /**
   * icon
   */
  icon: {
    id: '7e4e9013-ece2-484c-9029-eb4f643b05ba',
    name: 'icon',
    externalId: undefined,
    folders: {},
  },
} as const;
