/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const collections = {
  /**
   * Default
   */
  default: {
    codename: 'default',
    id: '00000000-0000-0000-0000-000000000000',
    name: 'Default',
  },
} as const;
