/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const contentTypeSnippets = {
  /**
   * Button
   */
  button: {
    codename: 'button',
    id: '7d93139f-749c-4e42-baa7-c87df6f36c1f',
    externalId: undefined,
    name: 'Button',
    elements: {
      /**
       * Button Text (text)
       */
      button__button_text: {
        codename: 'button__button_text',
        id: '41b61d48-dc48-4f06-a6e9-f2903ff2f482',
        externalId: undefined,
        name: 'Button Text',
        required: false,
        type: 'text',
      },

      /**
       * Button URL (text)
       */
      button__button_url: {
        codename: 'button__button_url',
        id: 'f8783aa9-4ae2-40b7-a783-8de6b1a12311',
        externalId: undefined,
        name: 'Button URL',
        required: false,
        type: 'text',
      },
    },
  },
} as const;
