/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const contentTypes = {
  /**
   * Card
   */
  choice_option: {
    codename: 'choice_option',
    id: 'ff98500d-a517-4c46-822c-1cedeeb41cf0',
    externalId: undefined,
    name: 'Card',
    elements: {
      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: 'cde986a9-6f6a-41e3-b847-0e6a669aa162',
        externalId: undefined,
        name: 'Description',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * Image (asset)
       */
      image: {
        codename: 'image',
        id: '43685bfd-b08e-4287-a4df-2e99fe605270',
        externalId: undefined,
        name: 'Image',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Habit
   */
  habit: {
    codename: 'habit',
    id: '3ca60cfe-e622-4e5f-a0d6-24f86634da4f',
    externalId: undefined,
    name: 'Habit',
    elements: {
      /**
       * Description (text)
       */
      description: {
        codename: 'description',
        id: 'd3a7b871-929f-4e36-ad8e-22e19d6df100',
        externalId: undefined,
        name: 'Description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * habit list items (modular_content)
       */
      habit_list_items: {
        codename: 'habit_list_items',
        id: 'e5b5ede8-89c2-47f2-b9f2-c50d73e26f46',
        externalId: undefined,
        name: 'habit list items',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Headline (text)
       */
      headline: {
        codename: 'headline',
        id: 'eeda7f2d-6816-4b38-85b2-af6ed60749c6',
        externalId: undefined,
        name: 'Headline',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * showcase Image (asset)
       */
      showcase_image: {
        codename: 'showcase_image',
        id: '00505385-d696-47ce-bab5-f4738439fea1',
        externalId: undefined,
        name: 'showcase Image',
        required: true,
        type: 'asset',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Habit list
   */
  habit_list: {
    codename: 'habit_list',
    id: '568058c8-1a86-4175-8a7d-162142b62d9b',
    externalId: undefined,
    name: 'Habit list',
    elements: {
      /**
       * Sustainability Categories (taxonomy)
       */
      category: {
        codename: 'category',
        id: 'ba31b553-e5ef-4294-afc8-9fee63b8e694',
        externalId: undefined,
        name: 'category',
        required: false,
        type: 'taxonomy',
        snippetCodename: undefined,
      },

      /**
       * icons (asset)
       */
      icons: {
        codename: 'icons',
        id: 'c2fed236-b6d2-4338-a012-b56941ebb5e3',
        externalId: undefined,
        name: 'icons',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * short description (text)
       */
      short_description: {
        codename: 'short_description',
        id: 'cb32b3fe-138b-424e-bb86-b693678c46a0',
        externalId: undefined,
        name: 'short description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Introduction Section
   */
  hero_introduction: {
    codename: 'hero_introduction',
    id: '71eecbdd-8624-421a-8235-cf8cfd4f7b8e',
    externalId: undefined,
    name: 'Introduction Section',
    elements: {
      /**
       * Button Text (text)
       */
      button__button_text: {
        codename: 'button__button_text',
        id: '41b61d48-dc48-4f06-a6e9-f2903ff2f482',
        externalId: undefined,
        name: 'Button Text',
        required: false,
        type: 'text',
        snippetCodename: 'button',
      },

      /**
       * Button URL (text)
       */
      button__button_url: {
        codename: 'button__button_url',
        id: 'f8783aa9-4ae2-40b7-a783-8de6b1a12311',
        externalId: undefined,
        name: 'Button URL',
        required: false,
        type: 'text',
        snippetCodename: 'button',
      },

      /**
       * description (text)
       */
      description: {
        codename: 'description',
        id: 'c9895f3b-2191-473b-a329-9563320e802e',
        externalId: undefined,
        name: 'description',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * hero image or logo (asset)
       */
      hero_image: {
        codename: 'hero_image',
        id: 'b8776382-d0a9-42c9-bca3-eefbb9cd3e0b',
        externalId: undefined,
        name: 'hero image or logo',
        required: false,
        type: 'asset',
        snippetCodename: undefined,
      },

      /**
       * Tagline (text)
       */
      tagline: {
        codename: 'tagline',
        id: 'e244b4e7-cfad-4cf7-a2a6-2453a674ceb9',
        externalId: undefined,
        name: 'Tagline',
        required: true,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Page
   */
  page: {
    codename: 'page',
    id: '377105e4-d8e6-41f1-9e19-0ab4ad18d09e',
    externalId: undefined,
    name: 'Page',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: '2c5c68b1-9c7d-4f4a-84ce-b1bfadb600dd',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Show in navigation (multiple_choice)
       */
      show_in_navigation: {
        codename: 'show_in_navigation',
        id: '82e34861-7161-4d58-b8a8-635af658c05a',
        externalId: undefined,
        name: 'Show in navigation',
        required: false,
        type: 'multiple_choice',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: 'b99657b5-f287-4fa1-b042-7c48ddd40e94',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '8c8e9e9d-7c8e-4c70-b6c2-6df15fdc46ed',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },

      /**
       * URL (url_slug)
       */
      url: {
        codename: 'url',
        id: '22db54d8-db09-4377-872a-30461d151ee3',
        externalId: undefined,
        name: 'URL',
        required: false,
        type: 'url_slug',
        snippetCodename: undefined,
      },
    },
  },

  /**
   * Web spotlight root
   */
  web_spotlight_root: {
    codename: 'web_spotlight_root',
    id: 'b219ba63-5194-456f-a95b-548c6d156a32',
    externalId: undefined,
    name: 'Web spotlight root',
    elements: {
      /**
       * Content (modular_content)
       */
      content: {
        codename: 'content',
        id: 'd693ad66-8e57-4378-9909-5cb2df1aabdf',
        externalId: undefined,
        name: 'Content',
        required: false,
        type: 'modular_content',
        snippetCodename: undefined,
      },

      /**
       * Subpages (subpages)
       */
      subpages: {
        codename: 'subpages',
        id: 'ade3178a-8505-45d5-9636-11e8b67b22c7',
        externalId: undefined,
        name: 'Subpages',
        required: false,
        type: 'subpages',
        snippetCodename: undefined,
      },

      /**
       * Title (text)
       */
      title: {
        codename: 'title',
        id: '944f08d0-5121-48c2-9758-e6c8dc6a1320',
        externalId: undefined,
        name: 'Title',
        required: false,
        type: 'text',
        snippetCodename: undefined,
      },
    },
  },
} as const;
