/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: 'project-manager',
    id: '87fa2e34-0b54-47b4-96b8-b521a4c1d0b9',
    name: 'Project manager',
  },
} as const;
