/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Project name: Sustainability_Project
 * Environment: Production
 * Project Id: bcb19f57-ab55-00ba-bbbc-10148965c370
 */
export const taxonomies = {
  /**
   * Asset
   */
  asset_: {
    codename: 'asset_',
    id: '34854ee5-b569-465e-a1c8-c3b0b2591a15',
    externalId: undefined,
    name: 'Asset ',
    terms: {
      food: {
        codename: 'food',
        id: '52b6f93e-9899-4675-ba1e-31fed8548ab2',
        externalId: undefined,
        name: 'Food',
        terms: {},
      },
      home: {
        codename: 'home',
        id: '77b86d32-3477-4f4f-ae11-1f847b980840',
        externalId: undefined,
        name: 'Home',
        terms: {},
      },
      recycle_repurpose_reuse: {
        codename: 'recycle_repurpose_reuse',
        id: 'b5750044-b379-4184-b382-6ab5c657ac5e',
        externalId: undefined,
        name: 'Recycle/Repurpose/Reuse',
        terms: {},
      },
      save_energy: {
        codename: 'save_energy',
        id: '86c86888-1652-433d-adb4-b320f30514ef',
        externalId: undefined,
        name: 'Save Energy',
        terms: {},
      },
    },
  },

  /**
   * Sustainability Categories
   */
  sustainability_categories: {
    codename: 'sustainability_categories',
    id: '8b9ee8d1-29b3-40b0-b649-e729b22246f7',
    externalId: undefined,
    name: 'Sustainability Categories',
    terms: {
      food_: {
        codename: 'food_',
        id: 'bff26a31-514f-454c-b85a-f06f2b8cdd5b',
        externalId: undefined,
        name: 'Food ',
        terms: {},
      },
      generic_habits: {
        codename: 'generic_habits',
        id: '82724edf-20d2-4a8c-a48e-a3dac36be9a9',
        externalId: undefined,
        name: 'Generic habits',
        terms: {},
      },
      recycle: {
        codename: 'recycle',
        id: 'a4e623cf-416e-4d69-95d3-2fe26e8d3191',
        externalId: undefined,
        name: 'Recycle',
        terms: {},
      },
      repurpose: {
        codename: 'repurpose',
        id: '661a4351-eaa7-471d-a907-c3456fa269f0',
        externalId: undefined,
        name: 'Repurpose',
        terms: {},
      },
      reuse: {
        codename: 'reuse',
        id: 'f9caac5e-9aa0-4000-bcf0-cc903f64aa05',
        externalId: undefined,
        name: 'Reuse',
        terms: {},
      },
      save_energy: {
        codename: 'save_energy',
        id: 'c78253f8-e869-4d00-b6de-69a3d7d02ec1',
        externalId: undefined,
        name: 'Save energy',
        terms: {},
      },
      save_water: {
        codename: 'save_water',
        id: '74c15e5c-bf1c-4b35-a26a-4752518ba938',
        externalId: undefined,
        name: 'Save water',
        terms: {},
      },
    },
  },
} as const;
